version: "3.9"

name: greenlight

services:
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: always
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_MAX_MESSAGES: 5000
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
  db:
    image: postgres:13.1-alpine
    container_name: db
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE?}
      POSTGRES_USER: ${DB_ROOT_USER?}
      POSTGRES_PASSWORD: ${DB_ROOT_PASSWORD?}
      PGDATA: "/var/lib/postgresql/data/pgdata"

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  pg-data:
